"""assinatura e pagamento_assinatura

Revision ID: 35a80494d517
Revises: c1356b7b8121
Create Date: 2026-09-13 19:50:43.565430
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# identificadores da revisão, usados pelo Alembic.
revision: str = '35a80494d517'
down_revision: Union[str, None] = 'c1356b7b8121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assinatura',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendedor_id', sa.UUID(), nullable=False),
    sa.Column('valido_ate', sa.Date(), nullable=False),
    sa.Column('origem', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assinatura_vendedor_id'), 'assinatura', ['vendedor_id'], unique=True)
    op.create_table('pagamento_assinatura',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendedor_id', sa.UUID(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('arquivo_nome', sa.String(), nullable=False),
    sa.Column('arquivo_caminho', sa.String(), nullable=False),
    sa.Column('arquivo_tipo', sa.String(), nullable=False),
    sa.Column('situacao', sa.String(), nullable=False),
    sa.Column('enviado_em', sa.DateTime(), nullable=False),
    sa.Column('avaliado_em', sa.DateTime(), nullable=True),
    sa.Column('avaliado_por', sa.UUID(), nullable=True),
    sa.Column('observacao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagamento_assinatura_vendedor_id'), 'pagamento_assinatura', ['vendedor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagamento_assinatura_vendedor_id'), table_name='pagamento_assinatura')
    op.drop_table('pagamento_assinatura')
    op.drop_index(op.f('ix_assinatura_vendedor_id'), table_name='assinatura')
    op.drop_table('assinatura')
    # ### end Alembic commands ###
