"""template_mensagem

Revision ID: 8ad77e42e1b6
Revises: de3e1d98beca
Create Date: 2026-08-04 23:06:24.138551
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# identificadores da revisão, usados pelo Alembic.
revision: str = '8ad77e42e1b6'
down_revision: Union[str, None] = 'de3e1d98beca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_mensagem',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendedor_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('corpo', sa.Text(), nullable=False),
    sa.Column('is_padrao', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendedor_id', 'tipo', name='uq_template_vendedor_tipo')
    )
    op.create_index(op.f('ix_template_mensagem_vendedor_id'), 'template_mensagem', ['vendedor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_mensagem_vendedor_id'), table_name='template_mensagem')
    op.drop_table('template_mensagem')
    # ### end Alembic commands ###
