"""vendedor, configuracao e cliente

Revision ID: 9159c4d20fc0
Revises: 
Create Date: 2026-07-12 15:23:00.228678
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# identificadores da revisão, usados pelo Alembic.
revision: str = '9159c4d20fc0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendedor_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('whatsapp_numero', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('envio_auto_ativo', sa.Boolean(), nullable=False),
    sa.Column('interacao_habilitada', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendedor_id', 'whatsapp_numero', name='uq_cliente_vendedor_whatsapp')
    )
    op.create_index(op.f('ix_cliente_vendedor_id'), 'cliente', ['vendedor_id'], unique=False)
    op.create_table('vendedor',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('google_email', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('whatsapp_numero', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_email')
    )
    op.create_table('configuracao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendedor_id', sa.UUID(), nullable=False),
    sa.Column('dias_antecedencia_lembrete', sa.Integer(), nullable=False),
    sa.Column('horario_resumo', sa.Time(), nullable=False),
    sa.Column('resumo_ativo', sa.Boolean(), nullable=False),
    sa.Column('envio_auto_global', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['vendedor_id'], ['vendedor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendedor_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracao')
    op.drop_table('vendedor')
    op.drop_index(op.f('ix_cliente_vendedor_id'), table_name='cliente')
    op.drop_table('cliente')
    # ### end Alembic commands ###
