"""canal e email do resumo diario

Revision ID: aa2b01caa64f
Revises: daa996ffc7c6
Create Date: 2026-09-24 23:02:28.315673
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# identificadores da revisão, usados pelo Alembic.
revision: str = 'aa2b01caa64f'
down_revision: Union[str, None] = 'daa996ffc7c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuracao', sa.Column('canal_resumo', sa.String(), server_default='whatsapp', nullable=False))
    op.add_column('configuracao', sa.Column('email_resumo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuracao', 'email_resumo')
    op.drop_column('configuracao', 'canal_resumo')
    # ### end Alembic commands ###
