"""cobranca_log e resposta_devedor

Revision ID: c1356b7b8121
Revises: 8ad77e42e1b6
Create Date: 2026-08-25 22:54:51.774268
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# identificadores da revisão, usados pelo Alembic.
revision: str = 'c1356b7b8121'
down_revision: Union[str, None] = '8ad77e42e1b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cobranca_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendedor_id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=True),
    sa.Column('parcela_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('detalhe', sa.String(), nullable=True),
    sa.Column('enviado_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcela.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cobranca_log_cliente_id'), 'cobranca_log', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_cobranca_log_criado_em'), 'cobranca_log', ['criado_em'], unique=False)
    op.create_index(op.f('ix_cobranca_log_parcela_id'), 'cobranca_log', ['parcela_id'], unique=False)
    op.create_index(op.f('ix_cobranca_log_vendedor_id'), 'cobranca_log', ['vendedor_id'], unique=False)
    op.create_table('resposta_devedor',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendedor_id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('parcela_id', sa.UUID(), nullable=True),
    sa.Column('opcao', sa.String(), nullable=False),
    sa.Column('recebido_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcela.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resposta_devedor_cliente_id'), 'resposta_devedor', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_resposta_devedor_parcela_id'), 'resposta_devedor', ['parcela_id'], unique=False)
    op.create_index(op.f('ix_resposta_devedor_recebido_em'), 'resposta_devedor', ['recebido_em'], unique=False)
    op.create_index(op.f('ix_resposta_devedor_vendedor_id'), 'resposta_devedor', ['vendedor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resposta_devedor_vendedor_id'), table_name='resposta_devedor')
    op.drop_index(op.f('ix_resposta_devedor_recebido_em'), table_name='resposta_devedor')
    op.drop_index(op.f('ix_resposta_devedor_parcela_id'), table_name='resposta_devedor')
    op.drop_index(op.f('ix_resposta_devedor_cliente_id'), table_name='resposta_devedor')
    op.drop_table('resposta_devedor')
    op.drop_index(op.f('ix_cobranca_log_vendedor_id'), table_name='cobranca_log')
    op.drop_index(op.f('ix_cobranca_log_parcela_id'), table_name='cobranca_log')
    op.drop_index(op.f('ix_cobranca_log_criado_em'), table_name='cobranca_log')
    op.drop_index(op.f('ix_cobranca_log_cliente_id'), table_name='cobranca_log')
    op.drop_table('cobranca_log')
    # ### end Alembic commands ###
