"""foto do perfil do vendedor

Revision ID: daa996ffc7c6
Revises: 612e2956d2f8
Create Date: 2026-09-24 22:27:37.073601
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# identificadores da revisão, usados pelo Alembic.
revision: str = 'daa996ffc7c6'
down_revision: Union[str, None] = '612e2956d2f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendedor', sa.Column('foto_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendedor', 'foto_url')
    # ### end Alembic commands ###
