"""venda e parcela

Revision ID: de3e1d98beca
Revises: 9159c4d20fc0
Create Date: 2026-08-04 22:40:51.312248
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# identificadores da revisão, usados pelo Alembic.
revision: str = 'de3e1d98beca'
down_revision: Union[str, None] = '9159c4d20fc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venda',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendedor_id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('num_parcelas', sa.Integer(), nullable=False),
    sa.Column('data_primeira_parcela', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venda_cliente_id'), 'venda', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_venda_vendedor_id'), 'venda', ['vendedor_id'], unique=False)
    op.create_table('parcela',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('venda_id', sa.UUID(), nullable=False),
    sa.Column('numero_parcela', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('aguardando_confirmacao', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['venda_id'], ['venda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcela_venda_id'), 'parcela', ['venda_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parcela_venda_id'), table_name='parcela')
    op.drop_table('parcela')
    op.drop_index(op.f('ix_venda_vendedor_id'), table_name='venda')
    op.drop_index(op.f('ix_venda_cliente_id'), table_name='venda')
    op.drop_table('venda')
    # ### end Alembic commands ###
