"""whatsapp que recebe o resumo

Revision ID: ff6aa3d8bde9
Revises: aa2b01caa64f
Create Date: 2026-09-24 23:25:17.613273
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# identificadores da revisão, usados pelo Alembic.
revision: str = 'ff6aa3d8bde9'
down_revision: Union[str, None] = 'aa2b01caa64f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuracao', sa.Column('whatsapp_resumo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuracao', 'whatsapp_resumo')
    # ### end Alembic commands ###
